# Generated by Django 3.0.5 on 2020-04-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=255)),
                ('addres', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'permissions': (('full-client', 'Изменение, чтение, добавление клиентов'), ('limited-client', 'Чтение всей информации и изменение номера телефона и баланса')),
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarif_type', models.CharField(max_length=20)),
            ],
            options={
                'permissions': (('full-service', 'Полный доступ к таблице услуг'),),
            },
        ),
        migrations.CreateModel(
            name='rendered_service',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
            options={
                'permissions': (('create-rendered-service', 'Создвние новой оказаннной услуги'), ('read-rendered-service', 'Чтение оказанных услуг'), ('full-rendered-service', 'Полный доступ к оказанным услугам')),
            },
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('provide_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
            options={
                'permissions': (('full-provider', 'Полный доступ к таблице поставщиков'),),
            },
        ),
        migrations.CreateModel(
            name='provided_service',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
            options={
                'permissions': (('full-provided-service', 'Полный доступ к поставленным услугам'),),
            },
        ),
    ]
