# Generated by Django 3.0.5 on 2020-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200502_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendered_service',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
